

export const C = {
    ADD_CATEGORY: "ADD_CATEGORY",
    ADD_TASK : "ADD_TASK",
    TOGGLE_TODO : "TOGGLE_TODO",
    SHOW_ALL : 'SHOW_ALL',
    SHOW_COMPLETED : 'SHOW_COMPLETED',
    SHOW_ACTIVE : 'SHOW_ACTIVE'
}