

export const C = {
    ADD_CATEGORY: "ADD_CATEGORY",
    ADD_TASK : "ADD_TASK",
    TOGGLE_TODO : "TOGGLE_TODO",
    SHOW_ALL : 'SHOW_ALL',
    SHOW_COMPLETED : 'SHOW_COMPLETED',
    SHOW_ACTIVE : 'SHOW_ACTIVE',
    SELECTED_CATEGORY : 'SELECTED_CATEGORY',
    TOGGLE_TODO: 'TOGGLE_TODO',
    ACTIVATE_CATEGORY: 'ACTIVATE_CATEGORY',
    DELETE_TASK: 'DELETE_TASK',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    SET_VISIBILITY_FILTER:'SET_VISIBILITY_FILTER'
}